# Configuration file for ZERO ERR drive
vendor_id: 0x5A65726F
product_id: 0x00029252
assign_activate: 0x003c # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"

rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, default: 0}  # Control word
      - {index: 0x6060, sub_index: 0, type: uint16, default: 9}  # Modes of operation
      - {index: 0x607F, sub_index: 0, type: int32, default: 2000} # Max velocity
      - {index: 0x60FF, sub_index: 0, type: int32, command_interface: velocity, default: 0} # Target velocity

tpdo:  # TxPDO = transmit PDO Mapping 
  - index: 0x1A00
    channels:
      - {index: 0x6041, sub_index: 0, type: uint16}  # Status word
      - {index: 0x606C, sub_index: 0, type: int32, state_interface: velocity} # Actual velocity
      - {index: 0x6064, sub_index: 0, type: int32, state_interface: position} # Actual position
      - {index: 0x6077, sub_index: 0, type: int32, state_interface: effort} # Actual torque
        
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: enable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}